---
title: "Taller 2 R"
output: html_document
date: '2022-06-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


- Antes de iniciar, tenga en cuenta que este es un nuevo proyecto. No olvide crear un nuevo proyecto de R.

## Caso hipotético de trabajo


Usted es el responsable de la base de datos de casos positivos de COVID 19 en Colombia. Por tanto, es responsable por las solicitudes de información. 

La página donde usted ofrecer los datos de los casos positivos es: <https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data>



### Ejercicio 1


- El digitador cometió un error y cambio la palabra `hogar` por la palabra `casa`. Por lo tanto, se le solicita a usted que corrija este error. Por favor, escriba un código que resuelva este problema, la base de datos se va a actualizar y las posiciones de los datos pueden cambiar. Asegúrese que sin importar la fecha y la posisición de los datos en la base de datos, el código funcione.

*Pista: La vAriable podRía Estar esCritA de DIFERENTES formas.*

### Ejercicio 2

- Se requiere presentar las cifras sobre fallecimientos por COVID-19. Por favor reporte el número total de fallecimientos confirmados según grupo etario para cada mes durantte 2022.

*Pista 1: para la división de grupos etarios podría usar "Primera infancia" (0 a 5),"Infancia" (6 a 11),"Adolescencia" (12 a 18),"Juventud" (19 a 26),"Adultez" (27 a 59),"Adulto mayor" (60 a 71),"Viejo Viejo" (72 en adelante)*

*Pista 2: %Y/%m/%d no es el único formato que existe. Existen otros como %Y/%b/%d*

### Ejercicio 3

- Le solicitan una gráfica de las personas que reportaron enfermedad leve en la que se pueda observar la distinciónn por grupo etario y sexo. Por favor realice esta gráfica verificando que sea legible y los ejes y colores entendibles para cualquier público.

### Ejercicio 4

- El digitador *otra vez* cometió un error:  los datos de las personas entre 50 y 60 años registrados el día 2 de marzo de 2021 debían ser registrados el día 1 de marzo de 2021. Es importante destacar, estos problemas parecen ser repetitivos, Por favor cree una `función` para corregir este tipo de errores.


### Ejercicio 5

- Por favor cree una función que solicite los siguientes argumentos: base de datos y ciudad. Incluya dentro de la función un elemento tipo ggplot que grafique la incidencia semanal y que incluya el color rojo para fallecidos y verde para vivos. 

### Ejercicio 6

- Haciendo uso de la función del Ejercicio 5, por favor escoja 3 departamentos y grafique un comparativo durante 2021.

*Pista : puede usar la función __plot_grid__ de la librería __cowplot__*




### Autoría

_Primer Borrador_: Jose M Velasco

_Ajustes y correcciones_: Zulma M Cucunubá
